### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by mp1pro** [eckiesz/bwa-u3-jammming-prj#1]
We did not get the savePlaylist to work using async/await. Can you also update github with the rest of the supporting files like package.json and the public folder. Then comment below.

**Comment by eckiesz** [comment]
Sorry, I'm having all kinds of issues uploading files.  How do I upload folders?

**Comment by eckiesz** [comment]
sorry, trying to get the files to you.

**Comment by mp1pro** [comment]
Use this tutorial to add files to GIT,[ https://help.github.com/articles/adding-a-file-to-a-repository-using-the-command-line/ ]( https://help.github.com/articles/adding-a-file-to-a-repository-using-the-command-line/ )
